version: 2.1

caches:
  - &yarn_cache derive-music-v1-{{ checksum "yarn.lock" }}

jobs:
  build:
    docker:
      - image: circleci/node
    working_directory: ~/derive-music
    steps:
      - checkout
      - restore_cache:
          key: *yarn_cache
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: *yarn_cache
          paths:
            - ./node_modules
      - run:
          name: Unit Tests
          command: yarn test
      - run:
          name: Gatsby Build
          command: CONTENTFUL_SPACE_ID="$CONTENTFUL_SPACE_ID" CONTENTFUL_ACCESS_TOKEN="$CONTENTFUL_ACCESS_TOKEN" yarn build
      - run:
          name: Firebase Deploy
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"
