version: 2.1

executors:
  default:
    working_directory: ~/derive-music
    docker:
      - image: circleci/node

caches:
  - &yarn_cache derive-music-v1-{{ checksum "yarn.lock" }}

commands:
  defaults:
    steps:
      - checkout
      - restore_cache:
          key: *yarn_cache
      - run:
          name: Installing Dependencies
          command: yarn install
      - save_cache:
          key: *yarn_cache
          paths:
            - ./node_modules
  linters:
    steps:
      - run:
          name: Running linters
          command: yarn lint
  tests:
    steps:
      - run:
          name: Running tests
          command: yarn test
  deploy:
    steps:
      - run:
          name: Building Gatsby
          command: CONTENTFUL_SPACE_ID="$CONTENTFUL_SPACE_ID" CONTENTFUL_ACCESS_TOKEN="$CONTENTFUL_ACCESS_TOKEN" yarn build
      - run:
          name: Deploying to Firebase
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"

jobs:
  linters:
    executor: default
    steps:
      - defaults
      - linters
  tests:
    executor: default
    steps:
      - defaults
      - tests
  deploy:
    executor: default
    steps:
      - defaults
      - deploy

workflows:
  version: 2.1
  build:
    jobs:
      - linters
      - tests
      - deploy:
          requires:
            - linters
            - tests
          filters:
            branches:
              only: master
